FROM alpine:3.15

# Installs  Chromium (93) package.
RUN apk add --no-cache \
  "chromium~=93.0.4577.82" \
  nss \
  freetype \
  freetype-dev \
  harfbuzz \
  ca-certificates \
  ttf-freefont \
  nodejs \
  npm \
  graphicsmagick \
  build-base \
  g++ \
  cairo-dev \
  jpeg-dev \
  pango-dev \
  giflib-dev \
  && addgroup -S -g 1000 pptruser && adduser -S -u 1000 -g pptruser pptruser \
  && mkdir -p /home/pptruser/Downloads /app \
  && chown -R pptruser:pptruser /home/pptruser \
  && chown -R pptruser:pptruser /app

#Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
  PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

USER pptruser

WORKDIR /app

EXPOSE 4500

CMD ["npm", "run", "dev:docker"]
